### ISSUE TITLE
build error on example file

### ISSUE THREAD

**Issue by aspieln3r** [hsanjuan/ipfs-lite#152]
When I build the example file on ipfs-lite/examples/litepeer/litepeer.go I get the following error
```
> go build ipfslite.go
# command-line-arguments
./ipfslite.go:21:8: undefined: ipfslite.NewInMemoryDatastore
```

**Comment by aspieln3r** [comment]
The error is when I build the file separately. Build is successfull if I clone the repo and build inside the cloned repo. To build, I did:
1. download the example file
2. go mod init example.com/myipfs
3. go mod tidy
4. go build litepeer.go

**Comment by hsanjuan** [comment]
You're not importing ipfslite properly or at the right version I guess.
