### ISSUE TITLE
The gocid version is too old to support the parsing of the k51qzi5uq******** format CID.

### ISSUE THREAD

**Issue by longren610** [hsanjuan/ipfs-lite#177]
The gocid version is too old to support the parsing of the k51qzi5uq******** format CID.
![image](https://user-images.githubusercontent.com/26690413/133718790-8d5e37dd-d38d-40f3-9233-50bd96916676.png)
![image](https://user-images.githubusercontent.com/26690413/133718827-1b4e8ca2-11a1-469a-8d90-6a1794c30e67.png)

**Comment by hsanjuan** [comment]
I think should be fixed in latest versions.
