### ISSUE TITLE
PubSub

### ISSUE THREAD

**Issue by WnP** [hsanjuan/ipfs-lite#21]
Hello,

What about adding IPFS PubSub feature to `ipfs-lite`?
did you already try that?
did you find some difficulties implementing it?

I know it's one more feature which may not fit the lite side of this project, but it opens a lot of new area to explore on IPFS, especially for projects like grpc-ipfs-lite, android-ipfs-lite, and so on... which are based on `ipfs-lite`.

Let me know your thought.

**Comment by hsanjuan** [comment]
Hi, pubsub is not an IPFS feature, it's a libp2p feature.

Pubsub needs to be added on top of a libp2p node, the same one that it is passed to ipfs-lite and this can be done very easily and without any trouble when needed. Therefore, it does not make sense to handle pubsub inside this library.
