### ISSUE TITLE
Huge database of peers

### ISSUE THREAD

**Issue by vkost** [hsanjuan/ipfs-lite#281]
Hi,
I just ran into a strange situation, which is probably not caused by ipfslite itself, but it's a starting point for my inquiry. I run a few servers with ipfs peers, and my executable uses ipfslite (albeit a bit older version, 1.4.2). For peer database, it uses badger storage. I found 55Gb of data on one server, and 58Gb on the other. I was wondering, is this to be expected, or maybe it has something to do with the storage choice. I have some other peers running ipfslite, but using MongoDB as the storage for the peer database. To what I can see, they don't have this problem.

Thank you - any info would be appreciated.

**Comment by hsanjuan** [comment]
Badger v1 leaves a lot of trash behind and GC is not very effective, so that's probably the problem. v3 works better. Pebble also works better.
