### ISSUE TITLE
Upgrade go-libp2p-core (and others) to latest

### ISSUE THREAD

**Issue by koalalorenzo** [hsanjuan/ipfs-lite#5]
I have noticed some changes in `go-libp2p-core` and it would be nice to have the latest stable and usable versions. 

Currently go-libp2p-core is set to v0.0.3, while v0.0.6 is out there (and it brings a set of breaking changes. semver convention missing here). Not required, but to avoid problems it would be nice to have it upgraded!

**Comment by hsanjuan** [comment]
I have updated deps ;-)
