### ISSUE TITLE
Add File wrapped in Directory

### ISSUE THREAD

**Issue by cbluth** [hsanjuan/ipfs-lite#7]
would it be possible to add a file wrapped in a directory with this library?

**Comment by hsanjuan** [comment]
No, but I'm sure it is not too difficult to create the wrapping node and add that as well:

https://godoc.org/github.com/ipfs/go-unixfs#EmptyDirNode
https://godoc.org/github.com/ipfs/go-merkledag#ProtoNode.AddRawLink

**Comment by cbluth** [comment]
@hsanjuan 

i have an issue here: https://github.com/distributed-mind/pagesaver/issues/2

i would like to move my project to ipfslite, but i would like to specify filenames of the files i add to ipfs

**Comment by hsanjuan** [comment]
@cbluth I am saying that your problem is easily solvable outside ipfs-lite. And that I would start by trying something like:

```go
// peer is the ipfs-lite peer instance
node := peer.AddFile(...) // add the file
emptyDir := unixfs.EmptyDirNode()
emptyDir.AddNodeLink("YOUR FILE NAME", node)
peer.Add(emptyDir) // add the wrapping folder

// emptyDir.Cid() should be the cid of the wrapping folder.
```

**Comment by cbluth** [comment]
@hsanjuan 

ah, right, thanks for straight forward response, and the code snippet!
